version: '3.9'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx_logs:/var/log/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  apache:
    image: httpd:latest
    container_name: apache
    ports:
      - "8082:80"
    volumes:
      - ./apache_logs:/usr/local/apache2/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  envoy:
    image: envoyproxy/envoy:v1.32.1
    container_name: envoy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./envoy_logs:/var/log/envoy:rw
    ports:
      - "8080:8080"
      - "9901:9901"  # Envoy Admin interface
    depends_on:
      - nginx
      - apache
      - otel-collector


  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    ports:
      - "4317:4317"    # gRPC receiver for OTLP
      - "55680:55680"  # OpenTelemetry receiver for traces
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    command: ["--config", "/etc/otel-config.yaml"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
